/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllBox: typeof import('./src/components/AllFunc/AllBox.vue')['default']
    AllFunc: typeof import('./src/components/AllFunc/AllFunc.vue')['default']
    AllSet: typeof import('./src/components/AllFunc/AllSet.vue')['default']
    CategoryAdd: typeof import('./src/components/LinkPanel/Category/CategoryAdd.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LinkAdd: typeof import('./src/components/LinkPanel/Link/LinkAdd.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH6: typeof import('naive-ui')['NH6']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    OtherSetting: typeof import('./src/components/setting/OtherSetting.vue')['default']
    Provider: typeof import('./src/components/Provider.vue')['default']
    SearchEngine: typeof import('./src/components/SearchInput/SearchEngine.vue')['default']
    SearchInp: typeof import('./src/components/SearchInput/SearchInp.vue')['default']
    ShortCut: typeof import('./src/components/AllFunc/Box/ShortCut.vue')['default']
    Suggestions: typeof import('./src/components/SearchInput/Suggestions.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    WeatherTime: typeof import('./src/components/WeatherTime.vue')['default']
  }
}
